from typing import Dict, Generator, List, Tuple


class SudokuDecart:
    range10 = ...
    cleanSudoku = ...

    def __init__(self, decart= None) -> None: ...

    def insert(self, x: int, y: int, num: int): ...

    def randInsert(self, x: int = None, y: int = None, n: int = None): ...

    def get(self, x: int, y: int) -> int: ...

    def getList(self, *coord: Tuple[int,int]) -> List[int]: ...

    def remove(self, x: int, y: int) -> int: ...

    def clean(self): ...

    def row(self, y: int) -> List[int]: ...

    def rowList(self) -> Generator[List[int],None,None]: ...

    def column(self, x: int) -> List[int]: ...

    def columnList(self) -> Generator[List[int],None,None]: ...

    def area(self, x: int, y: int) -> List[int]: ...

    def nArea(self, ax: int, ay: int) -> List[int]: ...

    def areaList(self) -> Generator[List[int],None,None]: ...

    @property
    def check(self) -> bool: ...

    @property
    def checkDepublicate(self) -> bool: ...

    def checkCoordDepublicate(self, x: int, y: int) -> bool: ...
